#!/usr/bin/env python3
"""Builds the SQL that loads public.word_bank from content/*/day-*.csv.

Courses go easiest first; inside a course the days and the lines keep their order.
Words already used earlier (case-insensitive) are skipped, and each topic is cut to
WORDS_PER_TOPIC words. Usage:

    python3 scripts/build_word_bank.py > supabase/migrations/<timestamp>_word_bank_data.sql
"""

import glob
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
COURSES = [
    ('content/a1-start', '1. Начало A1'),
    ('content/a2-next', '2. Дальше A2'),
    ('content/a2-confident', '3. Уверенный A2'),
    ('content/towards-b1', '4. Путь к B1'),
    ('content/b1-level', '5. Уровень B1'),
]
# The first two courses were loaded as they are; new ones are trimmed to this size.
WORDS_PER_TOPIC = 25
# Other correct answers accepted when typing (see starter_synonyms migration).
SYNONYMS = {
    'hello': 'hi, hey', 'goodbye': 'bye, bye-bye', 'thank you': 'thanks', 'mother': 'mom, mum, mommy, mummy',
    'father': 'dad, daddy', 'child': 'kid', 'color': 'colour', 'grey': 'gray', 'stomach': 'belly, tummy',
    'T-shirt': 'tshirt, tee', 'trousers': 'pants', 'sweater': 'jumper, pullover', 'sofa': 'couch', 'shop': 'store',
    'taxi': 'cab', 'plane': 'airplane, aeroplane', 'bicycle': 'bike', 'big': 'large', 'small': 'little',
    'fast': 'quick', 'difficult': 'hard', 'happy': 'glad', 'exam': 'test, examination', 'car': 'automobile',
}


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def main() -> None:
    seen: set[str] = set()
    rows: list[str] = []
    skipped: list[str] = []
    for folder, course in COURSES:
        files = sorted(glob.glob(os.path.join(ROOT, folder, 'day-*.csv')), key=lambda f: int(f.rsplit('-', 1)[1][:-4]))
        trim = folder not in ('content/a1-start', 'content/a2-next')
        for path in files:
            lines = open(path, encoding='utf-8').read().strip().split('\n')
            topic = lines[0].lstrip('#').split('|')[0].strip()
            taken = 0
            for line in lines[1:]:
                fields = [f.strip() for f in line.split(';')]
                if len(fields) != 6 or not all(fields[:3]):
                    raise SystemExit(f'{path}: bad line: {line}')
                word, ru, az, example, ipa, pos = fields
                key = word.lower()
                if key in seen:
                    skipped.append(f'{os.path.basename(path)}:{word}')
                    continue
                if trim and taken >= WORDS_PER_TOPIC:
                    continue
                seen.add(key)
                taken += 1
                values = [course, topic, word, ru, az, example, ipa, pos, SYNONYMS.get(word, '')]
                rows.append(f"  ({len(rows) + 1}, {', '.join(q(v) for v in values)})")
            if trim and taken < WORDS_PER_TOPIC:
                print(f'warning: {path} has only {taken} new words', file=sys.stderr)
    if skipped:
        print(f'skipped repeats: {", ".join(skipped)}', file=sys.stderr)
    print(f'{len(rows)} words', file=sys.stderr)
    print('-- Generated by scripts/build_word_bank.py from content/*/day-*.csv. Do not edit by hand.')
    print('delete from public.word_bank;')
    print('insert into public.word_bank (position, course, topic, word, translation_ru, translation_az, example, ipa, pos, synonyms) values')
    print(',\n'.join(rows) + ';')


if __name__ == '__main__':
    main()
